### ISSUE TITLE
Failure to parse `min_data_pos <= id0_header.page_size` (14796 vs 8192)

### ISSUE THREAD

**Issue by emesare** [Vector35/idb-rs#11]
Privately shared `.i64` fails to parse with: `min_data_pos <= id0_header.page_size` (14796 vs 8192).

Magic words: `blah blah 33` entry: `PayloadRestrictions.dll.i64`

**Comment by rbran** [comment]
Could not reproduce the error on the latest version, instead got `unk3 is not zeroed`

The file contains this strange data on the header `napshot of PayloadRestrictions.dll` seems to be some kind of left over data. It's kind of odd, but similar behavior was seem in other parts of the idb file.

In any case, removing the requirement for the header to not contain random data solves this issue: https://github.com/Vector35/idb-rs/pull/13
