### ISSUE TITLE
Failure to parse IDB file

### ISSUE THREAD

**Issue by Zerotistic** [Vector35/idb-rs#16]
I am following the instructions from here: https://dev-docs.binary.ninja/guide/migration/migrationguideida.html#importing-data

After opening, I get:
`Unable to parse IDB file: Type::Function`

I can either send the binary and IDB through emails or in Slack's DMs.

**Comment by emesare** [comment]
Thank you for the issue, you can send the binary to mason@vector35.com or on slack with the same email. Thanks!

**Comment by emesare** [comment]
Binary and IDB can be found internally with `maximum assignment rank`.
